car_pred/auth.py
# auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User, Buyer, Seller
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from flask_login import login_user, login_required, logout_user, current_user

auth = Blueprint('auth', __name__)

@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()
        if user:
            hashed_password = user.password
            if hashed_password is None:
                flash('Error: User password is not set. Please contact support.', category='error')
            elif check_password_hash(hashed_password, password):
                flash("Logged in successfully", category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Incorrect password', category='error')
        else:
            flash('Email does not exist', category='error')

    return render_template('login.html', user=current_user)

@auth.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

@auth.route('/sign-up')
def sign_up():
    return render_template('choose_sign_up.html',user=current_user)

@auth.route('/sign-up/buyer', methods=['GET', 'POST'])
def sign_up_buyer():
    if request.method == 'POST':
        email = request.form.get("email")
        firstname = request.form.get("firstname")
        password = request.form.get("password")
        confirm_pass = request.form.get("confirmpass")

        user = User.query.filter_by(email=email).first()
        if user:
            flash('Email already exists', category='error')
        elif len(email) < 4:
            flash('Email must be greater than 3 characters', category='error')
        elif len(firstname) < 2:
            flash("First name must be greater than 1 character", category='error')
        elif password != confirm_pass:
            flash("Passwords don't match.", category='error')
        elif len(password) < 7:
            flash("Password must be at least 7 characters", category='error')
        else:
            hashed_password = generate_password_hash(password, method='pbkdf2:sha256')
            new_user = User(email=email, first_name=firstname, password=hashed_password, user_type='buyer')
            db.session.add(new_user)
            db.session.commit()

            new_buyer = Buyer(user_id=new_user.id)
            db.session.add(new_buyer)
            db.session.commit()

            flash('Account created', category='success')
            login_user(new_user, remember=True)
            return redirect(url_for('views.home'))

    return render_template('sign_up_buyer.html', user=current_user)

@auth.route('/sign-up/seller', methods=['GET', 'POST'])
def sign_up_seller():
    if request.method == 'POST':
        email = request.form.get("email")
        firstname = request.form.get("firstname")
        password = request.form.get("password")
        confirm_pass = request.form.get("confirmpass")

        user = User.query.filter_by(email=email).first()
        if user:
            flash('Email already exists', category='error')
        elif len(email) < 4:
            flash('Email must be greater than 3 characters', category='error')
        elif len(firstname) < 2:
            flash("First name must be greater than 1 character", category='error')
        elif password != confirm_pass:
            flash("Passwords don't match.", category='error')
        elif len(password) < 7:
            flash("Password must be at least 7 characters", category='error')
        else:
            hashed_password = generate_password_hash(password, method='pbkdf2:sha256')
            new_user = User(email=email, first_name=firstname, password=hashed_password, user_type='seller')
            db.session.add(new_user)
            db.session.commit()

            new_seller = Seller(user_id=new_user.id)
            db.session.add(new_seller)
            db.session.commit()

            flash('Account created', category='success')
            login_user(new_user, remember=True)
            return redirect(url_for('views.home'))

    return render_template('sign_up_seller.html', user=current_user)



@auth.route('/sign-up/admin', methods=['GET', 'POST'])
def sign_up_admin():
    if request.method == 'POST':
        email = request.form.get("email")
        firstname = request.form.get("firstname")
        password = request.form.get("password")
        confirm_pass = request.form.get("confirmpass")

        user = User.query.filter_by(email=email).first()
        if user:
            flash('Email already exists', category='error')
        elif len(email) < 4:
            flash('Email must be greater than 3 characters', category='error')
        elif len(firstname) < 2:
            flash("First name must be greater than 1 character", category='error')
        elif password != confirm_pass:
            flash("Passwords don't match.", category='error')
        elif len(password) < 7:
            flash("Password must be at least 7 characters", category='error')
        else:
            hashed_password = generate_password_hash(password, method='pbkdf2:sha256')
            new_user = User(email=email, first_name=firstname, password=hashed_password, user_type='admin')
            db.session.add(new_user)
            db.session.commit()

            new_seller = Admins(user_id=new_user.id)
            db.session.add(new_seller)
            db.session.commit()

            flash('Account created', category='success')
            login_user(new_user, remember=True)
            return redirect(url_for('views.home'))

    return render_template('Admin_Signup.html', user=current_user)






car_pred/views.py
from flask import Blueprint, render_template, request, redirect, url_for, jsonify,flash, send_from_directory
from flask_login import login_required, current_user
from .models import Car

views = Blueprint('views', __name__)

@views.route('/')
@login_required
def home():
    return render_template('home.html', user=current_user)

@views.route('/marketplace', methods=['GET'])
def marketplace():
    if current_user.user_type != 'buyer' and not current_user.is_admin:
        flash('Only buyers can access this page.', category='error')
        return redirect(url_for('views.home'))
    cars = Car.query.all()
    return render_template('marketplace.html',  cars=cars, user=current_user)

@views.route('/uploads/<filename>')
def display_image(filename):
    return send_from_directory('static/uploads', filename)






car_pred/templates/base.html
<!DOCTYPE html>
<html>
<head xmlns="http://www.w3.org/1999/xhtml">
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>

    <link rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
          crossorigin="anonymous"/>
    <link rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
          crossorigin="anonymous"/>
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css"/>

    <title>{% block title %}Home{% endblock %}</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">
            {% if user.is_authenticated %}
                <a class="nav-item nav-link" id="home" href="/">Home</a>
                
                {% if user.user_type == 'buyer' %}
                <a class="nav-item nav-link" id="marketplace" href="/marketplace">Marketplace</a>
                {% endif %}
                <a class="nav-item nav-link" id="predict-price" href="/predict-price">Predict</a>
                {% if user.user_type == 'seller' %}
                <a class="nav-item nav-link" id="sell" href="/sell">Sell</a>
                {% endif %}
                 <a class="nav-item nav-link" id="admin" href="/marketplace" {% if not user.is_admin %}style="display:none;"{% endif %}>
                marketplace</a>
                <a class="nav-item nav-link" id="admin" href="/sell" {% if not user.is_admin %}style="display:none;"{% endif %}>
                sell</a>
                <a class="nav-item nav-link" id="admin" href="/admin" {% if not user.is_admin %}style="display:none;"{% endif %}>
                admin</a>
                
                <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>

               
                
            {% else %}
                <a class="nav-item nav-link" id="login" href="/login">Login</a>
                <a class="nav-item nav-link" id="signUp" href="/sign-up">Sign Up</a>
            {% endif %}
        </div>
    </div>
</nav>

{% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        {% for category, message in messages %}
            {% if category == 'error' %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% else %}
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}
{% endwith %}

<div class="container">
    {% block content %}{% endblock %}
</div>

<footer class="bg-dark text-white mt-4">
    <div class="container py-4">
        <div class="row">
            <div class="col text-center">
                <h5>Connect with us</h5>
                <a href="https://www.facebook.com" class="text-white mx-2" target="_blank">
                    <i class="fab fa-facebook fa-2x"></i>
                </a>
                <a href="https://www.twitter.com" class="text-white mx-2" target="_blank">
                    <i class="fab fa-twitter fa-2x"></i>
                </a>
                <a href="https://www.instagram.com" class="text-white mx-2" target="_blank">
                    <i class="fab fa-instagram fa-2x"></i>
                </a>
            </div>
        </div>
    </div>
</footer>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-qN6ZYFN1RbSoGGI4plkht7K3Qywr1OTq2a5Rt6AqO4BsnjQ5VUKU9k9Q4e2etKJN"
        crossorigin="anonymous"></script>
</body>
</html>

car_pred/templates/choose_sign_up.html
{% extends "base.html" %}
{% block title %}Sign Up{% endblock %}
{% block content %}

<style>
    .background-image {
        background-image: url('static/car_signup.jpg'); /* Update this path to your image */
        background-size: inherit;
        background-position: center;
        height: 100vh; /* Adjust the height as needed */
        display: flex;
        justify-content: center;
        align-items: center;
        text-align: center;
        color: white; /* Ensure the text is readable */
    }

    .content-overlay {
        background: rgba(0, 0, 0, 0.5); /* Optional: Adds a dark overlay for better readability */
        padding: 20px;
        border-radius: 10px;
    }

    .content-overlay h2 {
        margin-bottom: 20px;
    }

    .content-overlay .btn {
        margin: 10px;
    }
</style>

<div class="background-image">
    <div class="content-overlay">
        <h2>Choose Sign Up Type</h2>
        <a class="btn btn-primary" href="{{ url_for('auth.sign_up_buyer') }}">Sign Up as Buyer</a>
        <a class="btn btn-secondary" href="{{ url_for('auth.sign_up_seller') }}">Sign Up as Seller</a>
    </div>
</div>
{% endblock %}

car_pred/templates/home.html
{% extends "base.html" %}

{% block content %}
<style>
  .background-image {
    background-image: url('static/car_login.png');
    background-size: cover;
    background-position: center;
    height: 100vh;
    display: flex;
    justify-content: center;
    align-items: center;
    flex-direction: column; /* Allows stacking cards vertically */
  }
  
  .card-custom {
    background: rgba(255, 255, 255, 0.8); /* Slightly transparent background */
    padding: 20px;
    border-radius: 10px;
    max-width: 600px;
    margin: 20px; /* Adds space between cards */
  }
</style>

<div class="background-image">
  <div class="card card-custom">
    <div class="card-body text-center">
      <h2 class="card-title">Car Buying/Selling</h2>
    </div>
  </div>

  <div class="card card-custom">
    <div class="card-body text-center">
    {% if user.user_type=='buyer' or user.is_admin %}      
    <button class="btn btn-primary" onclick="location.href='/marketplace'">Go to Marketplace</button>
    {% endif %}
    {% if user.user_type=='seller' or user.is_admin %}
      <button class="btn btn-success" onclick="location.href='/sell'">Sell Your Car</button>
      {% endif %}
      <button class="btn btn-secondary" onclick="location.href='predict-price'">Predict Your Car Price</button>
    </div>
  </div>
</div>

{% endblock %}

car_pred/templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="card mt-50" style="width: 100%; height: 100%">
            <div class="card-header" style="text-align: center">
                <h1> Car Price Predictor</h1>
            </div>
            <div class="card-body">
                <div class="col-12" style="text-align: center">
                    <h5>This app predicts the price of a car you want to sell. Try filling the details below:</h5>
                </div>
                <br>
                <form method="post" action="{{ url_for('pred.predict') }}" accept-charset="utf-8" name="Modelform">
                    <div class="col-md-10 form-group" style="text-align: center">
                        <label><b>Select the company:</b></label><br>
                        <select class="selectpicker form-control" id="company" name="company" required="1" onchange="load_car_models(this.id, 'car_models')">
                            {% for company in companies %}
                            <option value="{{ company }}">{{ company }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="col-md-10 form-group" style="text-align: center">
                        <label><b>Select the model:</b></label><br>
                        <select class="selectpicker form-control" id="car_models" name="car_models" required="1">
                        </select>
                    </div>
                    <div class="col-md-10 form-group" style="text-align: center">
                        <label><b>Select Year of Purchase:</b></label><br>
                        <select class="selectpicker form-control" id="year" name="year" required="1">
                            {% for year in years %}
                            <option value="{{ year }}">{{ year }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="col-md-10 form-group" style="text-align: center">
                        <label><b>Select the Fuel Type:</b></label><br>
                        <select class="selectpicker form-control" id="fuel_type" name="fuel_type" required="1">
                            {% for fuel in fuel_types %}
                            <option value="{{ fuel }}">{{ fuel }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="col-md-10 form-group" style="text-align: center">
                        <label><b>Enter the Number of Kilometres that the car has travelled:</b></label><br>
                        <input type="text" class="form-control" id="kilo_driven" name="kilo_driven" placeholder="Enter the kilometres driven ">
                    </div>
                    <div class="col-md-10 form-group" style="text-align: center">
                        <button type="submit" class="btn btn-primary form-control">Predict Price</button>
                    </div>
                </form>
                <br>
                <div class="row">
                    <div class="col-12" style="text-align: center">
                        <h4><span id="prediction"></span></h4>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    function load_car_models(company_id, car_model_id) {
        var company = document.getElementById(company_id);
        var car_model = document.getElementById(car_model_id);
        console.log(company.value);
        car_model.value = "";
        car_model.innerHTML = "";
        {% for company in companies %}
        if (company.value == "{{ company }}") {
            {% for model in car_models %}
            {% if company in model %}
            var newOption = document.createElement("option");
            newOption.value = "{{ model }}";
            newOption.innerHTML = "{{ model }}";
            car_model.options.add(newOption);
            {% endif %}
            {% endfor %}
        }
        {% endfor %}
    }
</script>

<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7HUiBZ39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
{% endblock %}

car_pred/templates/login.html
{% extends 'base.html' %}

{% block content %}

<style>
    .background-image {
        background-image: url('static/car_login.png'); /* Update this path to your image */
        background-size: cover;
        background-position: center;
        height: 100vh; /* Adjust the height as needed */
        display: flex;
        justify-content: center;
        align-items: center;
        text-align: center;
    }

    .login-form {
        background: rgba(255, 255, 255, 0.8); /* Optional: Adds a light overlay for better readability */
        padding: 30px;
        border-radius: 10px;
        max-width: 600px;
        width: 100%;
    }

    .login-form h1 {
        margin-bottom: 20px;
    }
</style>

<div class="background-image">
    <div class="login-form">
        <form method='POST'>
            <div class="card-header" style="text-align: center">
                <h1>Login</h1>
            </div>
            <div class="form-group">
                <label for="email">Email Address</label>
                <input type="email" class="form-control" id="email" name="email" placeholder="Enter Email" required>
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" class="form-control" id="password" name="password" placeholder="Enter Password" required>
            </div>
            <br/>
            <button type="submit" class="btn btn-primary btn-block">Login</button>
        </form>
    </div>
</div>

{% endblock %}

car_pred/templates/marketplace.html
<!-- templates/marketplace.html -->
{% extends "base.html" %}

{% block title %}Marketplace{% endblock %}

{% block content %}
<div class="container mt-5">
    <h1 class="mb-4">Available Cars</h1>
    <div class="row">
        {% for car in cars %}
        <div class="col-md-4 mb-4">
            <div class="card">
                {% if car.image %}
                <img class="card-img-top" src="{{ url_for('views.display_image', filename=car.image) }}" alt="Car Image">
                {% else %}
                <img class="card-img-top" src="{{ url_for('views.display_image', filename='default-car.png') }}" alt="Default Car Image">
                {% endif %}
                <div class="card-body">
                    <h5 class="card-title">{{ car.car_name }} - {{ car.company }}</h5>
                    <p class="card-text">Year: {{ car.year_of_purchase }}</p>
                    <p class="card-text">Price: ${{ car.price }}</p>
                    <p class="card-text">KMs Driven: {{ car.kms_driven }}</p>
                    <p class="card-text">Fuel Type: {{ car.fuel_type }}</p>
                    <p class="card-text">Address: {{ car.address }}</p>
                    <p class="card-text bg-primary text-white p-2 rounded">Contact: {{ car.contact_details }}</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

car_pred/templates/pred.html
{% extends 'base.html' %}


{% block content%}




</script>


<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>

    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
{% endblock %}

car_pred/templates/result.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="card mt-50" style="width: 100%; height: 100%">
            <div class="card-header" style="text-align: center">
                <h1>Prediction Result</h1>
            </div>
            <div class="card-body">
                <div class="col-12" style="text-align: center">
                    <h4>Prediction: ₹{{ prediction }}</h4>
                    <p><b>Selected Company:</b> {{ company }}</p>
                    <p><b>Selected Model:</b> {{ car_model }}</p>
                    <p><b>Year of Purchase:</b> {{ year }}</p>
                    <p><b>Fuel Type:</b> {{ fuel_type }}</p>
                    <p><b>Kilometers Driven:</b> {{ driven }}</p>
                    <a href="{{ url_for('pred.index') }}" class="btn btn-primary">Predict Another Price</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

car_pred/templates/sell.html
<!-- templates/sell.html -->
{% extends "index.html" %}
{% block title %}Sell Car{% endblock %}
{% block content %}
<h2>Sell Your Car</h2>
<form method="POST" action="/sell" enctype="multipart/form-data">
    <div class="form-group">
        <label for="car_name">Car Name</label>
        <input type="text" class="form-control" id="car_name" name="car_name" required>
    </div>
    <div class="form-group">
        <label for="company">Company</label>
        <input type="text" class="form-control" id="company" name="company" required>
    </div>
    <div class="form-group">
        <label for="year_of_purchase">Year of Purchase</label>
        <input type="number" class="form-control" id="year_of_purchase" name="year_of_purchase" required>
    </div>
    <div class="form-group">
        <label for="price">Price</label>
        <input type="number" class="form-control" id="price" name="price" required>
    </div>
    <div class="form-group">
        <label for="kms_driven">Kms Driven</label>
        <input type="number" class="form-control" id="kms_driven" name="kms_driven" required>
    </div>
    <div class="form-group">
        <label for="fuel_type">Fuel Type</label>
        <input type="text" class="form-control" id="fuel_type" name="fuel_type" required>
    </div>
    <div class="form-group">
        <label for="owner_name">Owner Name</label>
        <input type="text" class="form-control" id="owner_name" name="owner_name" required>
    </div>
    <div class="form-group">
        <label for="address">Address</label>
        <input type="text" class="form-control" id="address" name="address" required>
    </div>
    <div class="form-group">
        <label for="contact_details">Contact Details</label>
        <input type="text" class="form-control" id="contact_details" name="contact_details" required>
    </div>
    <div class="form-group">
        <label for="image">Car Image</label>
        <input type="file" class="form-control-file" id="image" name="image" required>
    </div>
    <button type="submit" class="btn btn-primary">List Car for Sale</button>
</form>
{% endblock %}

car_pred/templates/seller.html
seller.html
<html>
<head>
</head>
	<title></title>
	<body>
		<form>
  			<div class="form-group">
			    <label for="exampleInputEmail1">Email address</label>
			    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
			    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>

</form>

	</body>
</html>

car_pred/templates/sign-up.html
{% extends 'base.html' %}

{% block content %}

<form method='POST'>
	<H3 align="center">SIGN-UP</h3>
		<div class="form-group">
			<label for="email">EmailAddress</label>
			<input type="email" class="form-control" id="email" name="email" placeholder="Enter Email" >

		</div>

		<div class="form-group">
			<label for="firstname">First Name</label>
			<input type="text" class="form-control" id="firstname" name="firstname" placeholder="Enter first name"  >

		</div>



		<div class="form-group">
			<label for="password">Password</label>
			<input type="password" class="form-control" id="password" name="password" placeholder="Enter password" >

		</div>

		<div class="form-group">
			<label for="confirmpass">Confirm password</label>
			<input type="password" class="form-control" id="Last Name" name="confirmpass" placeholder="confirm password" >

		</div>
		<br/>

		<button type="submit" class="btn btn-primary">Submit</button>
</form>

{% endblock %}

car_pred/templates/sign_up_buyer.html
{% extends "base.html" %}
{% block title %}Sign Up Seller{% endblock %}
{% block content %}
<form method="POST" action="{{ url_for('auth.sign_up_buyer') }}">
    <div class="form-group">
        <label for="email">Email</label>
        <input type="email" class="form-control" id="email" name="email" required>
    </div>
    <div class="form-group">
        <label for="firstname">First Name</label>
        <input type="text" class="form-control" id="firstname" name="firstname" required>
    </div>
    <div class="form-group">
        <label for="password">Password</label>
        <input type="password" class="form-control" id="password" name="password" required>
    </div>
    <div class="form-group">
        <label for="confirmpass">Confirm Password</label>
        <input type="password" class="form-control" id="confirmpass" name="confirmpass" required>
    </div>
    <button type="submit" class="btn btn-primary">Sign Up</button>
</form>
{% endblock %}

car_pred/templates/sign_up_seller.html
{% extends "base.html" %}
{% block title %}Sign Up Seller{% endblock %}
{% block content %}
<form method="POST" action="{{ url_for('auth.sign_up_seller') }}">
    <div class="form-group">
        <label for="email">Email</label>
        <input type="email" class="form-control" id="email" name="email" required>
    </div>
    <div class="form-group">
        <label for="firstname">First Name</label>
        <input type="text" class="form-control" id="firstname" name="firstname" required>
    </div>
    <div class="form-group">
        <label for="password">Password</label>
        <input type="password" class="form-control" id="password" name="password" required>
    </div>
    <div class="form-group">
        <label for="confirmpass">Confirm Password</label>
        <input type="password" class="form-control" id="confirmpass" name="confirmpass" required>
    </div>
    <button type="submit" class="btn btn-primary">Sign Up</button>
</form>
{% endblock %}